### ISSUE TITLE
Migrate from a `setup.py` file to a `pyproject.toml` setup file

### ISSUE THREAD

**Issue by armstjc** [spyoungtech/FreeSimpleGUI#11]
As detailed in this article, the Python community has largely moved from using `setup.py` as the way to define a python project setup file, to the `pyproject.toml` standard:
https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

Currently, FreeSimpleGUI does not currently use the newer `pyproject.toml` standard.
![Screenshot_1](https://github.com/spyoungtech/FreeSimpleGUI/assets/70788681/0cc6a154-2e4d-4663-816d-5087ba2083f7)

Does this project intend to move to the newer `pyproject.toml` standard, or does it intend to stay on the increasingly outdated `setup.py` standard?

**Comment by spyoungtech** [comment]
The project uses `setup.cfg` not `setup.py` -- the presence of the `setup.py` file is only to maintain compatibility with clients that don't support PEP-517 builds.
