### ISSUE TITLE
Documentation url not working

### ISSUE THREAD

**Issue by PeterXiaoGuo** [spyoungtech/FreeSimpleGUI#15]
Hello, 

Is there any chance the documentation website will be back work? (http://www.freesimplegui.org/) I just noticed the url didn't work.

Thanks a lot.

**Comment by spyoungtech** [comment]
@PeterXiaoGuo please see #4 and continue discussion there.

I've got the domains, but just haven't gotten around to publishing anything there just yet.

But most of the documentation is available on ReadTheDocs: https://freesimplegui.readthedocs.io/en/latest/ (though not all links will work as expected, for the same reason)
