### ISSUE TITLE
Where is FreeSimpleGUI.py

### ISSUE THREAD

**Issue by wrwetzel** [spyoungtech/FreeSimpleGUI#17]
I found FreeSimpleGUIQt.py, FreeSimpleGUIWeb.py, and FreeSimpleGUIWx.py below similarly-named folders but I'm unable to find FreeSimpleGUI.py below the FreeSimpleGUI folder. I tried the .zip file and cloning the source.

Please help.
Thanks,
Bill

**Comment by spyoungtech** [comment]
Hi Bill,

In the current development version on the main branch, the primary `FreeSimpleGUI` package is no longer a single module. It is being refactored into a proper package with multiple modules. Hence, there is no single `FreeSimpleGUI.py` file available.

The last released version tag is still more or less a single module. It can be found here: https://github.com/spyoungtech/FreeSimpleGUI/blob/v5.1.0/FreeSimpleGUI/FreeSimpleGUI.py

**Comment by wrwetzel** [comment]
Thanks for your detailed answer. Unfortunately pip complains:  _error: externally-managed-environment_ on Arch. One option is to install in a virtual environment or I could, and probably will, wait until _python-freesimplegui_ makes it into the Arch repository, as is the case for _python-pysimplegui_. 

Thanks again,
Bill
