### ISSUE TITLE
Error calling the button color chooser

### ISSUE THREAD

**Issue by pgoetzke** [spyoungtech/FreeSimpleGUI#18]
In line 5499 of the FreeSimpleGUI.py file, the attempt to use the Button Color Chooser leads to the error message: "AttributeError: 'Button' object has no attribute 'default_color'". The problem can be solved locally by removing the attribute "color=self.default_color". But of course the error occurs again with every new installation, especially in the pipeline. Best regards

**Comment by spyoungtech** [comment]
Thanks for the report. Can you please share some minimal code that can be used to reproduce this problem?

**Comment by spyoungtech** [comment]
Closing this due to being stale. If you still have this problem, feel free to comment here and I'll reopen, or feel free to open a new issue.
