### ISSUE TITLE
thank you for your effort i wanted to add a note [SystemTray]

### ISSUE THREAD

**Issue by Red0Hood** [spyoungtech/FreeSimpleGUI#19]
there is another library linked to this one where it add tray support

[PySimpleGUI/psgtray](https://github.com/PySimpleGUI/psgtray)

env\Lib\site-packages\psgtray\psgtray.py
changing pysimplegui to
 import FreeSimpleGUI as sg
line 14
would make it work with no problem

**Comment by spyoungtech** [comment]
Thanks. The `psgtray.py` in this repository should have this update. I don't control the [PySimpleGUI/psgtray](https://github.com/PySimpleGUI/psgtray) project (which seems to be more or less the same as the `psgtray.py` file in this repo?), so obviously I cannot update it :)
