### ISSUE TITLE
mailinglist / forum / contact ?

### ISSUE THREAD

**Issue by horstjens** [spyoungtech/FreeSimpleGUI#22]
Is there a mailinglist, a webforum, contact email or a recommended method to communicate with the author(s) of FreeSimpleGUI (other than writing issues)?

**Comment by spyoungtech** [comment]
Hi @horstjens and thanks for raising this question.

Right now, GitHub is the best way to get in contact for any inquiries surrounding FreeSimpleGUI. Whether it's to report a bug, ask a question, request a feature, or even just share something on your mind about FreeSimpleGUI, all inquiries are welcome through GitHub.

In addition to GitHub issues, I've also just enabled the [discussions](https://github.com/spyoungtech/FreeSimpleGUI/discussions) page for those who are more comfortable with that format.
