### ISSUE TITLE
Optimize the association method between events and functions

### ISSUE THREAD

**Issue by yunluo** [spyoungtech/FreeSimpleGUI#26]
Currently, within the GUI library, one has to write a 'while True' loop and use 'if' statements to implement functionality. This method is usable but not elegant. I have created an additional library that uses decorators to associate events with functions. Can the GUI library be made to have a similar built-in mechanism?

**Comment by spyoungtech** [comment]
I'm not sure exactly what that may look like, but yes, I believe there is a lot of room to improve the provided event-driven patterns in the library.

**Comment by yunluo** [comment]
https://github.com/yunluo/pyguievent

A simple self-use event method that I wrote myself, I wrote poorly, I think you can write better
