### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by brucehchurch** [spyoungtech/FreeSimpleGUI#34]
Tried to link to www.FreeSimpleGUI.org as indicated in the documentation but the web site does not exists. I checked whois. It appears that the domain is not available. Other than the documentation available for the software that FreeSImpleGUI was forked from, are there any other sites that provide documentation specific to FreeSimpleGUI.

Thank you.

**Comment by spyoungtech** [comment]
You can find the docs on readthedocs: https://freesimplegui.readthedocs.io/en/latest/

Otherwise, see #4 about this link in particular.
