### ISSUE TITLE
Documentation link is dead

### ISSUE THREAD

**Issue by schellenberg** [spyoungtech/FreeSimpleGUI#5]
Links to documentation on the http://[www.freesimplegui.org](http://www.freesimplegui.org/)/ website do not work.

**Comment by spyoungtech** [comment]
Thanks for the report. Yeah, as mentioned in #4 -- the freesimplegui websites as well as corrections to the documentation are currently a work-in-progress, but eventually those links will work. Please use #4 if you want to continue discussion on the topic.
